import test from 'node:test';import assert from 'node:assert/strict';import {transition,viewState,DB} from '../server/engine.js';
const config=(n=2,expansion=false,seed=91)=>({config:{players:Array.from({length:n},(_,i)=>({name:'Player '+i,isAI:true})),expansion,seed}});
async function newState(n=2,expansion=false,seed=91){return(await transition(config(n,expansion,seed),{type:'start'})).state}
function physical(g){return [...g.main,...g.flavor,...g.flavorDis,...g.abyss,...g.tarotDiscard,...g.epicDeck,...g.epicTier.filter(Boolean),...g.gallery.filter(Boolean),...g.jug,...g.extraGallery,...g.players.flatMap(p=>[...p.deck,...p.hand,...p.discard,...p.inPlay,...p.items,...p.fiends])]}
test('printed base components: 107 main, 30 Flavor, 21 Juggalos',async()=>{const g=await newState();assert.equal(g.main.length+g.gallery.length,107);assert.equal(g.flavor.length,30);assert.equal(g.jug.length,21);assert.deepEqual(g.players.map(p=>p.hand.length+p.deck.length),[10,10]);assert.equal(g.epicDeck.length+g.epicTier.length,8)});
test('wrong actions are rejected without mutating source state',async()=>{const g=await newState(),before=JSON.stringify(g);await assert.rejects(transition(g,{type:'play',id:999999}));await assert.rejects(transition(g,{type:'buy',zone:'gallery',index:0}));assert.equal(JSON.stringify(g),before)});
test('player views keep hands and draw order private',async()=>{const g=await newState();const v=viewState(g,0);assert(v.players[1].hand.every(x=>x===null));assert(v.players.every(p=>p.deck.every(x=>x===null)));assert(v.main.every(x=>x===null));assert(!('rng'in v));assert(!('config'in v))});
test('card choices replay deterministically and reject invalid answers',async()=>{const g=await newState(),p=g.players[g.active];p.isAI=false;const dog=p.hand.find(c=>c.id==='c1200')||p.deck.find(c=>c.id==='c1200');if(!p.hand.includes(dog)){p.deck.splice(p.deck.indexOf(dog),1);p.hand.push(dog)}const action={type:'play',id:dog.u};const first=await transition(g,action);assert.equal(first.pending.kind,'option');const result=await transition(g,action,[1]);assert.equal(result.pending,null);assert.equal(result.state.players[g.active].inPlay.at(-1).crewOverride,'PSY');await assert.rejects(transition(g,action,[99]));assert.deepEqual((await transition(g,action,[1])).state,result.state)});
test('all printed card effects can resolve with legal AI choices',async()=>{for(const d of DB){if(['TAROT','JUG','START','GAMBIT'].includes(d.t))continue;const g=await newState(2,true,4),p=g.players[g.active];const c={id:d.id,u:++g.uid,d,tilted:false,crewOverride:null};p.karma=20;if(d.t==='FIEND'){p.fiends.push(c);if(!d.fiendUse?.length)continue;await transition(g,{type:'fiend',id:c.u})}else if(d.t==='ITEM'){p.items.push(c);if(!d.active)continue;await transition(g,{type:'item',id:c.u})}else{p.hand.push(c);await transition(g,{type:'play',id:c.u})}}});
test('full base and expansion games preserve cards and end with equal turns',async()=>{for(const n of [2,3,4])for(const expansion of [false,true])for(let seed=1;seed<=5;seed++){let g=await newState(n,expansion,seed),steps=0;const expected=physical(g).length;while(!g.over&&steps++<2500){const r=await transition(g,{type:'bot'});assert.equal(r.pending,null);g=r.state;const cards=physical(g);assert.equal(new Set(cards.map(c=>c.u)).size,cards.length,`duplicate card n=${n} expansion=${expansion} seed=${seed} step=${steps}`);assert.equal(cards.length,expected,`lost card n=${n} expansion=${expansion} seed=${seed} step=${steps}`)}assert(g.over,'game should finish');assert(g.players.every(p=>p.turns===g.players[0].turns))}});
