import {transition,viewState} from './engine.js';
const encoder=new TextEncoder();
const json=(value,status=200,headers={})=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
function fail(status,message){throw new HttpError(status,message)}
function cleanName(value){const s=typeof value==='string'?value.trim():'';if(!s||s.length>24||/[<>\x00-\x1f]/.test(s))fail(400,'Use a name between 1 and 24 characters.');return s.replace(/[&"']/g,'')}
async function hash(s){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(s)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');
async function body(request){if(Number(request.headers.get('Content-Length'))>10000)fail(413,'Request too large.');let s=await request.text();if(s.length>10000)fail(413,'Request too large.');try{return JSON.parse(s)}catch{fail(400,'Invalid request.')}}
async function session(request,db){const c=(request.headers.get('Cookie')||'').match(/(?:^|;\s*)echo_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(c){const id=await hash(c);const found=await db.prepare('SELECT id FROM sessions WHERE id = ?').bind(id).first();if(found)return {id}}
const secret=token(),id=await hash(secret);await db.prepare('INSERT INTO sessions(id,created_at) VALUES (?,?)').bind(id,Date.now()).run();return{id,cookie:`echo_session=${secret}; HttpOnly; Path=/; SameSite=Lax; Max-Age=15552000${new URL(request.url).protocol==='https:'?'; Secure':''}`}}
async function load(db,code,sid){if(!/^[A-Z2-9]{8}$/.test(code))fail(404,'Room not found.');const row=await db.prepare('SELECT * FROM rooms WHERE code = ?').bind(code).first();if(!row)fail(404,'Room not found. Check the code.');const payload=JSON.parse(row.state),seat=payload.members.findIndex(x=>x.session===sid);return {row,payload,seat}}
function project(room){const {row,payload,seat}=room;if(seat<0)fail(403,'Join this room first.');return{code:row.code,revision:row.revision,status:row.status,seat,isHost:payload.members[0]?.session===payload.members[seat]?.session,expansion:payload.expansion,members:payload.members.map(m=>({name:m.name,isAI:!!m.isAI})),game:viewState(payload.game,seat),pending:payload.pending?payload.pending.actor===seat?payload.pending:{actor:payload.pending.actor,title:'A player is resolving a card effect.',kind:'waiting'}:null}}
async function save(db,room,status=room.row.status){const next=room.row.revision+1;const r=await db.prepare('UPDATE rooms SET state = ?, revision = ?, status = ?, updated_at = ? WHERE code = ? AND revision = ?').bind(JSON.stringify(room.payload),next,status,Date.now(),room.row.code,room.row.revision).run();if(!r.meta.changes)fail(409,'The table changed. Your view has been refreshed; try again.');room.row.revision=next;room.row.status=status;return project(room)}
async function execute(room,action,answers=[],base=null){const result=await transition(base||room.payload.game,action,answers);room.payload.game=result.state;room.payload.pending=result.pending;if(result.pending)room.payload.transaction={base:base||room.payload.transaction?.base,action,answers};else delete room.payload.transaction}
export default {async fetch(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(request);
if(!env.DB)return json({error:'The game service is temporarily unavailable.'},503);
try{if(!['GET','POST'].includes(request.method))fail(405,'Method not allowed.');if(request.method==='POST'){const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)fail(403,'Open the game directly to continue.');if(!request.headers.get('Content-Type')?.includes('application/json'))fail(415,'Expected JSON.')}
const s=await session(request,env.DB),headers=s.cookie?{'Set-Cookie':s.cookie}:{};
if(url.pathname==='/api/session'&&request.method==='GET'){const rooms=await env.DB.prepare('SELECT rooms.code, rooms.status, rooms.updated_at FROM seats JOIN rooms ON rooms.code=seats.room WHERE seats.session = ? ORDER BY rooms.updated_at DESC LIMIT 10').bind(s.id).all();return json({rooms:rooms.results},200,headers)}
if(url.pathname==='/api/rooms'&&request.method==='POST'){const b=await body(request),name=cleanName(b.name);if(b.tutorial&&!b.solo)fail(400,'The tutorial is a solo practice table.');const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM rooms WHERE host = ? AND updated_at > ?').bind(s.id,Date.now()-60000).first();if(count.n>=6)fail(429,'Please wait a moment before creating another table.');const code=Array.from(crypto.getRandomValues(new Uint8Array(8)),v=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[v%32]).join('');const members=[{name,session:s.id}];if(b.solo)members.push({name:'The Void',session:'bot:'+token(),isAI:true});const seed=crypto.getRandomValues(new Uint32Array(1))[0];const payload={members,expansion:b.tutorial?false:!!b.expansion,game:null,pending:null,seed};const room={row:{code,revision:0,status:b.solo?'playing':'lobby'},payload,seat:0};if(b.solo){const base={config:{players:members.map(m=>({name:m.name,isAI:m.isAI})),expansion:payload.expansion,seed,tutorial:!!b.tutorial}};await execute(room,{type:'start'},[],base)}await env.DB.batch([env.DB.prepare('INSERT INTO rooms(code,host,status,revision,state,updated_at) VALUES (?,?,?,?,?,?)').bind(code,s.id,room.row.status,0,JSON.stringify(payload),Date.now()),env.DB.prepare('INSERT INTO seats(id,room,session,seat) VALUES (?,?,?,?)').bind(code+':'+s.id,code,s.id,0)]);return json(project(room),201,headers)}
const match=url.pathname.match(/^\/api\/rooms\/([A-Z2-9]{8})(?:\/(join|start|action|choice|bot|tutorial))?$/);if(!match)fail(404,'Route not found.');const room=await load(env.DB,match[1],s.id),route=match[2];
if(!route&&request.method==='GET')return json(project(room),200,headers);
if(request.method!=='POST')fail(405,'Method not allowed.');const b=await body(request);
if(route==='join'){if(room.seat>=0)return json(project(room),200,headers);if(room.row.status!=='lobby')fail(409,'This match has already started.');if(room.payload.members.length>=4)fail(409,'This room is full.');const name=cleanName(b.name);room.seat=room.payload.members.length;room.payload.members.push({name,session:s.id});const out=await save(env.DB,room);await env.DB.prepare('INSERT OR REPLACE INTO seats(id,room,session,seat) VALUES (?,?,?,?)').bind(room.row.code+':'+s.id,room.row.code,s.id,room.seat).run();return json(out,200,headers)}
if(room.seat<0)fail(403,'Join this room first.');if(b.revision!==room.row.revision)fail(409,'The table changed. Refreshing your view.');
if(route==='start'){if(room.seat!==0)fail(403,'Only the host can start the match.');if(room.row.status!=='lobby'||room.payload.members.length<2)fail(409,'Wait for at least one other player.');const base={config:{players:room.payload.members.map(m=>({name:m.name,isAI:m.isAI})),expansion:room.payload.expansion,seed:room.payload.seed}};await execute(room,{type:'start'},[],base);return json(await save(env.DB,room,'playing'),200,headers)}
if(room.row.status!=='playing'||room.payload.game?.over)fail(409,'This match is over.');
if(route==='tutorial'){
if(room.seat!==0||!room.payload.game?.tutorial?.active)fail(403,'This table has no active guide for you.');
const command=b.action?.command;if(!['next','skip','finish'].includes(command))fail(400,'Invalid tutorial action.');
if(room.payload.pending&&command!=='skip')fail(409,'Resolve the card effect first.');
// Leaving during a choice restores the uncommitted move before removing guidance.
const base=room.payload.transaction?.base||room.payload.game;
await execute(room,{type:'tutorial',command},[],structuredClone(base));
return json(await save(env.DB,room),200,headers);
}
if(route==='choice'){const pending=room.payload.pending,tx=room.payload.transaction;if(!pending||!tx||pending.actor!==room.seat)fail(403,'Another player is resolving this effect.');const answers=[...tx.answers,b.answer];await execute(room,tx.action,answers,tx.base)}else{
if(room.payload.pending)fail(409,'Resolve the current card effect first.');const game=room.payload.game;if(route==='bot'){if(!game.players[game.active].isAI)fail(409,'The AI is not taking a turn.');await execute(room,{type:'bot'},[],structuredClone(game))}else{if(game.active!==room.seat)fail(403,'It is not your turn.');if(!b.action||!['play','ninjas','buy','cycle','item','fiend','unity','end'].includes(b.action.type))fail(400,'Invalid game action.');await execute(room,b.action,[],structuredClone(game))}}
return json(await save(env.DB,room,room.payload.game.over?'complete':'playing'),200,headers);
}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);if(/D1|SQLITE|database/i.test(e.message)){console.error('Game storage failure',e.message);return json({error:'The game service is unavailable. Your last confirmed move is safe. Please reconnect.'},503)}console.error('Game action failed',e.stack);return json({error:e.message||'This action could not be completed.'},400)}}};
