import { scenarios, resolveScenarioStep, KIT_VERSION } from './scenarios.js';
import { DB, viewState } from '../server/engine.js';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fixtures=await scenarios();let selected=fixtures[0],state=structuredClone(selected.setup),position=0,history=[];
const art=Object.fromEntries(DB.map(d=>[d.id,d.art]));const definitions=Object.fromEntries(DB.map(d=>[d.id,d]));
const download=(name,data)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const names=(cards,reverse=false)=>{let list=[...cards];if(reverse)list=list.toReversed();return list.length?list.map(c=>c ? `<button class="lab-card" data-card="${c.id}">${esc(c.d.n)}${c.crewOverride || c.d.t==='JUG'?' · '+(c.crewOverride || c.d.crew):''}${c.tilted?' · used':''}${c.nullTurn===state.turnN?' · nullified':''}</button>` : '<span class="empty-position">Empty slot</span>').join(''):'<span class="muted">Empty</span>';};
function pile(label,cards,reverse=false){return `<div class="lab-pile"><h4>${label}${reverse?' · top first':''}</h4><div>${names(cards,reverse)}</div></div>`;}
function render(){
 $('scenarios').innerHTML=fixtures.map(s=>`<button data-scenario="${s.id}" class="${selected===s?'primary':''}" aria-pressed="${selected===s}">${esc(s.title)}</button>`).join('');
 const s=selected,step=s.steps[position],top=state.variants?.mirrors?viewState(state,0):null;
 $('lesson').innerHTML=`<section class="lab-lesson"><span class="eyebrow">${s.oracle?'Oracle guided practice':'Variant practice'} · ${position} / ${s.steps.length} steps</span><h2>${esc(s.title)}</h2><p>${esc(s.lesson)}</p><div class="lab-action"><b>${step?'Next action':'Scenario complete'}</b><p>${esc(step?.label || 'Compare your physical table with the checks below. Restart to replay the same position.')}</p><button id="advance" class="primary" ${step?'':'disabled'}>${position?'Resolve next step':'Resolve first step'}</button><button id="restart">Reset this position</button>${!step?'<button id="next-lesson">Next lesson →</button>':''}</div><details ${position===s.steps.length?'open':''}><summary>Expected results after the last step</summary><ul>${s.checks.map(c=>`<li>${esc(c)}</li>`).join('')}</ul></details><p class="tiny">Active: ${esc(state.players[state.active].name)} · Turn ${state.turnN} · Final round: ${state.endTriggered?'yes':'no'} · Kit ${KIT_VERSION}</p></section><section class="lab-board" aria-label="Exact table position"><h2>Exact table position</h2>${top?`<p>Public tops: ${['main','epicDeck','flavor'].map(z=>`${z==='main'?'Main':z==='epicDeck'?'Epic':'Flavor'}: ${esc(top[z].at(-1)?.d.n || 'empty')}`).join(' · ')}</p>`:''}<div class="lab-players">${state.players.map(p=>`<article><h3>${esc(p.name)} · ${p.karma} Karma</h3><p>Unity ${p.unityUsed?'used':'available'} · ${p.turns} completed turns</p>${pile('Hand',p.hand)}${pile('Played cards',p.inPlay)}${pile('Items',p.items)}${pile('Fiends',p.fiends)}${pile('Gambits',p.gambits || [])}${pile('Discard',p.discard)}${pile('Deck',p.deck,true)}</article>`).join('')}</div>${state.relic?pile('Shared Relic · never owned',[state.relic]):''}${pile('Gallery · slots left to right',state.gallery)}${pile('Epic Tier · slots left to right',state.epicTier)}${pile('Main Deck',state.main,true)}${pile('Epic draw pile',state.epicDeck,true)}${pile('Flavor draw pile',state.flavor,true)}${pile('Flavor discard',state.flavorDis)}${pile('Juggalo deck',state.jug,true)}${pile('Abyss',state.abyss)}${pile('Resolved Tarot',state.tarotDiscard)}${pile('Removed Gambits',state.gambitRemoved || [])}</section><details class="lab-journal"><summary>Digital resolution journal</summary><ol>${state.log.map(l=>`<li>${esc(l.replace(/<\/?b>/g,''))}</li>`).join('') || '<li>No actions yet.</li>'}</ol></details>`;
 $('advance').onclick=async()=>{try{$('advance').disabled=true;state=await resolveScenarioStep(state,step);history.push(step);position++;render();$('lesson').scrollIntoView({block:'start'});}catch(e){$('report-status').textContent=e.message;}};
 $('restart').onclick=()=>select(s.id);if($('next-lesson'))$('next-lesson').onclick=()=>select(fixtures[(fixtures.indexOf(s)+1)%fixtures.length].id);
}
function select(id){selected=fixtures.find(s=>s.id===id)||fixtures[0];state=structuredClone(selected.setup);position=0;history=[];$('result').value='not-tested';$('physical').value='';$('evidence').value='';$('report-status').textContent='';render();location.hash=selected.id;}
document.addEventListener('click',e=>{const scenario=e.target.closest('[data-scenario]');if(scenario){select(scenario.dataset.scenario);return;}const card=e.target.closest('[data-card]');if(card){const id=card.dataset.card,d=definitions[id];if(!d)return;const dialog=$('lab-zoom');dialog.innerHTML=`<button id="close-zoom">Close</button><h2 id="zoom-title">${esc(d.n)}</h2>${art[id]?`<img src="../assets/cards/${art[id]}.jpg" alt="${esc(d.n)}">`:''}<p>${esc(d.txt)}</p>`;dialog.showModal();$('close-zoom').onclick=()=>dialog.close();}});
$('report-form').onsubmit=e=>{e.preventDefault();download(`echoside-${selected.id}-step-${position}-report.json`,{format:'echoside-physical-comparison',version:KIT_VERSION,recordedAt:new Date().toISOString(),scenario:selected.id,step:position,result:$('result').value,physical:$('physical').value,evidence:$('evidence').value,testers:$('testers').value,expected:selected.checks,actions:history,startingState:selected.setup,digitalState:state,userAgent:navigator.userAgent});$('report-status').textContent='Report prepared. Save it with your playtest notes.';};
$('print').onclick=()=>window.print();
select(location.hash.slice(1)||new URLSearchParams(location.search).get('lesson')||'unity');
